
x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: ''
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy
    gateway:
      condition: service_healthy
    kafka_spy:
      condition: service_healthy

services:
  zookeeper_spy:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper_spy
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost ${ZOOKEEPER_CLIENT_PORT} | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:14
    container_name: postgres_spy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter_spy
    ports:
      - "${PG_EXPORTER_PORT}:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://admin:admin@postgres_spy:5432/spy_platform?sslmode=disable
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_spy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${SUPERSET_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${SUPERSET_PASSWORD}
    ports:
      - "${PG_ADMIN_PORT}:80"
    depends_on:
      - postgres

  kafka_spy:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka_spy
    depends_on:
      - zookeeper_spy
    ports:
      - "${KAFKA_PORT}:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_spy:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_spy:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:${KAFKA_PORT}", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped


  kafdrop_spy:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop_spy
    ports:
      - "${KAFDROP_PORT}:9000"
    environment:
      KAFKA_BROKERCONNECT: ${KAFKA_BROKER_URL}
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka_spy


  backend:
    image: spy_backend:latest
    container_name: spy_backend
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - kafka_spy
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_spy
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "${CLICKHOUSE_PORT}:8123"
      - "${CLICKHOUSE_SERVICE_PORT}:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${CLICKHOUSE_PORT}/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5


  bot:
    image: spy_bot:latest
    container_name: spy_bot
    restart: unless-stopped
    build: ./bot
    ports:
      - "${BOT_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - kafka_spy
      - backend
      - redis



  logs:
    image: spy_logs:latest
    build: ./logs
    container_name: spy_logs
    ports:
      - ${LOGS_SERVICE_PORT}:8000
    env_file:
      - .env
    depends_on:
      - kafka_spy
      - backend
      - clickhouse
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${LOGS_SERVICE_PORT}/health"]


  price_saver:
    image: spy_price_saver:latest
    build: ./price_saver
    container_name: spy_price_saver
    ports:
      - ${PRICE_SAVER_PORT}:8000
    env_file:
      - .env
    depends_on:
      - kafka_spy
      - backend
      - clickhouse
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PRICE_SAVER_PORT}/health"]


  parser:
    image: spy_parser:latest
    build: ./parser
    container_name: spy_parser
    ports:
      - ${PARSER_PORT}:8000
    env_file:
      - .env
    depends_on:
      - kafka_spy
      - backend
      - clickhouse
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PARSER_PORT}/health"]


  gateway:
    image: spy_gateway:latest
    build: ./gateway
    container_name: spy_gateway
    ports:
      - ${GATEWAY_PORT}:8000
    env_file:
      - .env
    depends_on:
      - kafka_spy
      - backend
      - clickhouse
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${GATEWAY_PORT}/health"]



  redis:
    image: redis:7
    container_name: redis_spy
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  clickhouse_ui:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_ui
    ports:
      - "${CLICKHOUSE_UI_PORT}:8123"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_HTTP_PORT=8123
      - CLICKHOUSE_LISTEN_HOST=0.0.0.0
    depends_on:
      - clickhouse


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_spy
    ports:
      - "${NODE_EXPORTER_PORT}:9100"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'


  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor_spy
    ports:
      - "${CADVISOR_PORT}:8080"
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka_exporter_spy
    ports:
      - "${KAFKA_EXPORTER_PORT}:9308"
    restart: unless-stopped
    command:
      - --kafka.server=${KAFKA_BROKER_URL}
      - --web.listen-address=:9308
      - --log.level=info

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter_spy
    ports:
      - "${REDIS_EXPORTER_PORT}:9121"
    restart: unless-stopped
    environment:
      - REDIS_ADDR=${REDIS_ADDR}

  clickhouse-exporter:
    image: flant/clickhouse-exporter:latest
    container_name: clickhouse_exporter_spy
    ports:
      - "${CLICKHOUSE_EXPORTER_PORT}:9116"
    restart: unless-stopped
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_URL=${CLICKHOUSE_URL}

  superset:
    image: apache/superset:latest
    container_name: superset_spy
    env_file:
      - .env
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    ports:
      - "${SUPERSET_PORT}:8088"
    volumes:
      - superset_data:/app/superset_home
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  superset-init:
    image: apache/superset:latest
    container_name: superset_init_spy
    env_file:
      - .env
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    volumes:
      - superset_data:/app/superset_home
    command: [
        "sh", "-c",
        "superset fab create-admin --username ${SUPERSET_USERNAME} --firstname ${POSTGRES_FIRSTNAME} --lastname ${POSTGRES_LASTNAME} --email ${SUPERSET_EMAIL} --password ${SUPERSET_PASSWORD} && superset db upgrade && superset init"
      ]
    depends_on:
      - postgres
    profiles:
      - init


  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "${AIRFLOW_WEBSERVER_PORT}:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow


volumes:
  clickhouse_data:
  redis_data:
  grafana_data:
  prometheus_data:
  postgres_data:
  superset_data:
  dbeaver_data:

