global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'django_backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /metrics
    scrape_interval: 10s
    honor_labels: true


  - job_name: 'stats_logs'
    static_configs:
      - targets: ['logs:8002']
    metrics_path: /metrics
    scrape_interval: 10s


  - job_name: 'stats_analytics'
    static_configs:
      - targets: ['analytics:8001']
    metrics_path: /metrics
    scrape_interval: 10s


  - job_name: 'bot_service'
    static_configs:
      - targets: ['bot:8080']
    metrics_path: /metrics
    scrape_interval: 10s


  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 15s


  - job_name: 'clickhouse_exporter'
    static_configs:
      - targets: ['clickhouse-exporter:9116']
    scrape_interval: 20s


  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 20s


  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s


  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets: []


rule_files: []